<?xml version="1.0"?>
<robot name="em_3905" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="lidar.xacro"/>
  <xacro:include filename="properties.xacro"/>
  <xacro:include filename="macros.xacro"/>

  <link name="base_footprint">
  </link>
  <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="base_footprint"/>
  </joint>
  <!-- base_link must have geometry so that its axes can be displayed in
       rviz. -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="chassis_mat"/>
    </visual>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- Chassis -->
  <link name="chassis">
    <visual>
      <!-- <origin xyz="0 0 ${-chassis_height / 2}"/> -->
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="chassis_mat"/>
    </visual>

    <collision>
      <!-- <origin xyz="0 0 ${-chassis_height / 2}"/> -->
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>

    <xacro:solid_cuboid_inertial
        width="${chassis_length}" depth="${chassis_width}"
        height="${chassis_height}" mass="${chassis_mass}">
      <origin xyz="0 0 0"/>
    </xacro:solid_cuboid_inertial>
  </link>
  <gazebo reference="chassis">
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="base_link_to_chassis" type="fixed">
      <origin xyz="0.0 0.0 0.0"/>
    <parent link="base_link"/>
    <child link="chassis"/>
  </joint>


  <!-- Wheels -->
  <xacro:front_wheel lr_prefix="left" fr_prefix="front"
                     lr_reflect="1" fr_reflect="1"/>
  <xacro:front_wheel lr_prefix="right" fr_prefix="front"
                     lr_reflect="-1" fr_reflect="1"/>
  <xacro:rear_wheel lr_prefix="left" fr_prefix="rear"
                    lr_reflect="1" fr_reflect="-1"/>
  <xacro:rear_wheel lr_prefix="right" fr_prefix="rear"
                    lr_reflect="-1" fr_reflect="-1"/>
</robot>
